CREATE TABLE posts (
  id INT GENERATED ALWAYS AS IDENTITY,
  guid VARCHAR NOT NULL,
  author VARCHAR NOT NULL,
  title VARCHAR NOT NULL,
  date VARCHAR NOT NULL,
  body VARCHAR NOT NULL,
  likes VARCHAR NOT NULL
);
